# Site settings
title: "SHOCKWAVE: Brand Mastery Academy"
description: "We teach entrepreneurs and creators how to build powerful personal brands based on timeless biblical principles."
url: "https://rualdo12.github.io/Rualdo-Kruger.github.io/"
# Build settings
theme: jekyll-theme-minimal
